dynamic:
  data-source:
    mysql_1:
      url: jdbc:mysql://192.168.0.104:3306/db01?Unicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false
      username: db01
      password: 123456
      driver-class-name: com.mysql.jdbc.Driver
    mysql_2:
      url: jdbc:mysql://192.168.0.104:3306/db02?Unicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false
      username: db02
      password: 123456
      driver-class-name: com.mysql.jdbc.Driver


